# Generated by Django 6.1 on 2026-08-29 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_prodotto_pubblicazione_alter_prodotto_taglia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutazione', models.IntegerField(choices=[(1, '1 stella'), (2, '2 stelle'), (3, '3 stelle'), (4, '4 stelle'), (5, '5 stelle')])),
                ('commento', models.TextField(blank=True, max_length=300)),
                ('data', models.DateField(auto_now_add=True)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensione', to='catalog.prodotto')),
            ],
            options={
                'unique_together': {('prodotto', 'acquirente')},
            },
        ),
    ]
