# Generated by Django 6.1 on 2026-08-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_prodotto_pubblicazione_alter_prodotto_taglia'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='catalog.prodotto'),
        ),
    ]
