# Generated by Django 6.1 on 2026-09-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_recensione_prodotto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recensione',
            options={'verbose_name_plural': 'Recensioni'},
        ),
    ]
