# Generated by Django 6.1 on 2026-09-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_ricerca_taglia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ricerca',
            options={'verbose_name_plural': 'Consigliati'},
        ),
    ]
