# Generated by Django 6.1 on 2026-08-31 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_prodotto_pubblicazione_alter_prodotto_taglia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(default='completato', max_length=15)),
                ('data_acquisto', models.DateField(auto_now_add=True)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.prodotto')),
            ],
        ),
    ]
