# Generated by Django 6.1 on 2026-08-24 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('sneakers', 'Sneakers'), ('running', 'Running'), ('eleganti', 'Eleganti'), ('stivali', 'Stivali'), ('sandali', 'Sandali')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('immagine', models.ImageField(upload_to='prodotti_img/')),
                ('taglia', models.IntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.TextField(default='Nessuna descrizione.', max_length=300)),
                ('disponibile', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.categoria')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
