# Generated by Django 6.1 on 2026-08-25 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='pubblicazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='taglia',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
