# Generated by Django 6.1 on 2026-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_categoria_options_alter_prodotto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
