# Generated by Django 6.1 on 2026-09-04 17:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_prodotto_prezzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='taglia',
            field=models.DecimalField(choices=[(Decimal('35.0'), '35'), (Decimal('35.5'), '35.5'), (Decimal('36.0'), '36'), (Decimal('36.5'), '36.5'), (Decimal('37.0'), '37'), (Decimal('37.5'), '37.5'), (Decimal('38.0'), '38'), (Decimal('38.5'), '38.5'), (Decimal('39.0'), '39'), (Decimal('39.5'), '39.5'), (Decimal('40.0'), '40'), (Decimal('40.5'), '40.5'), (Decimal('41.0'), '41'), (Decimal('41.5'), '41.5'), (Decimal('42.0'), '42'), (Decimal('42.5'), '42.5'), (Decimal('43.0'), '43'), (Decimal('43.5'), '43.5'), (Decimal('44.0'), '44'), (Decimal('44.5'), '44.5'), (Decimal('45.0'), '45'), (Decimal('45.5'), '45.5')], decimal_places=1, max_digits=3),
        ),
    ]
