# Generated by Django 6.1 on 2026-08-30 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_prodotto_pubblicazione_alter_prodotto_taglia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aggiunta', models.DateField(auto_now_add=True)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.prodotto')),
            ],
            options={
                'unique_together': {('prodotto', 'acquirente')},
            },
        ),
    ]
