# Generated by Django 6.1 on 2026-09-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferito',
            options={'verbose_name_plural': 'Preferiti'},
        ),
    ]
